<?php
require_once __DIR__ . '/config/db.php';
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/includes/validation.php';
require_once __DIR__ . '/includes/layout.php';

if (isLoggedIn()) {
    redirect('index.php');
}

$role = (($_POST['role'] ?? $_GET['role'] ?? 'Student') === 'Admin') ? 'Admin' : 'Student';
$departments = $pdo->query('SELECT deptid, deptname, facultyname FROM department ORDER BY deptname')->fetchAll();

$old = [
    'name' => '', 'email' => '', 'username' => '', 'deptid' => '',
    'semester' => '', 'cgpa' => '',
];
$errors = [];

if (isPost()) {
    foreach ($old as $k => $_) {
        $old[$k] = trim((string) ($_POST[$k] ?? ''));
    }
    $password = (string) ($_POST['password'] ?? '');
    $confirm  = (string) ($_POST['confirm_password'] ?? '');

    if (!verifyCsrfToken()) {
        $errors[] = 'Your session expired. Please reload the page and try again.';
    } else {
        $errors = collect_errors(
            v_name($old['name'], 'Full name'),
            v_username($old['username']),
            v_password($password, $confirm)
        );

        if ($role === 'Student') {
            $errors = array_merge($errors, collect_errors(
                v_email($old['email']),
                v_required($old['deptid'], 'Department'),
                v_semester($old['semester']),
                v_cgpa($old['cgpa'], true)
            ));
            if ($old['deptid'] !== '') {
                $d = $pdo->prepare('SELECT 1 FROM department WHERE deptid = ?');
                $d->execute([$old['deptid']]);
                if (!$d->fetch()) {
                    $errors[] = 'Please select a valid department.';
                }
            }
        } else {
            $code = (string) ($_POST['admin_code'] ?? '');
            if ($code === '' || !hash_equals(ADMIN_REGISTRATION_CODE, $code)) {
                $errors[] = 'The admin registration code is incorrect.';
            }
        }

        if (!$errors) {
            $q = $pdo->prepare('SELECT 1 FROM users WHERE username = ?');
            $q->execute([$old['username']]);
            if ($q->fetch()) {
                $errors[] = 'This username is already taken. Please choose another one.';
            }
            if ($role === 'Student') {
                $q = $pdo->prepare('SELECT 1 FROM student WHERE email = ?');
                $q->execute([$old['email']]);
                if ($q->fetch()) {
                    $errors[] = 'An account with this email already exists.';
                }
            }
        }

        if (!$errors) {
            try {
                $pdo->beginTransaction();

                $ins = $pdo->prepare('INSERT INTO users (username, passwordhash, role) VALUES (?, ?, ?)');
                $ins->execute([$old['username'], password_hash($password, PASSWORD_BCRYPT), $role]);

                // userid is generated by a trigger -> read it back by the unique username
                $u = $pdo->prepare('SELECT userid FROM users WHERE username = ?');
                $u->execute([$old['username']]);
                $userid = $u->fetchColumn();

                if ($role === 'Student') {
                    $s = $pdo->prepare('INSERT INTO student (userid, deptid, name, email, cgpa, semester) VALUES (?, ?, ?, ?, ?, ?)');
                    $s->execute([$userid, $old['deptid'], $old['name'], $old['email'], $old['cgpa'], (int) $old['semester']]);
                } else {
                    $a = $pdo->prepare('INSERT INTO admin (userid, name) VALUES (?, ?)');
                    $a->execute([$userid, $old['name']]);
                }

                $pdo->commit();
                set_app_cookie(COOKIE_LAST_ROLE, $role, 365);
                finish('success', "$role account created. You can now sign in.", 'login.php?role=' . $role);
            } catch (PDOException $ex) {
                if ($pdo->inTransaction()) {
                    $pdo->rollBack();
                }
                $errors[] = $ex->getCode() === '23000'
                    ? 'That username or email is already in use.'
                    : 'Registration failed because of a database error. Please try again.';
            }
        }
    }
}

ajax_errors($errors);

page_start('Register');
?>
<?php auth_open(true); ?>
    <h1 class="auth-title">Create your account</h1>
    <p class="auth-sub">Register as <?= $role === 'Admin' ? 'an admin' : 'a student' ?>. Fields marked <span class="text-danger">*</span> are required.</p>

    <div class="role-switch">
        <a href="?role=Student" class="<?= $role === 'Student' ? 'active' : '' ?>"><i class="bi bi-person"></i> Student</a>
        <a href="?role=Admin" class="<?= $role === 'Admin' ? 'active' : '' ?>"><i class="bi bi-shield-lock"></i> Admin</a>
    </div>

    <?php if ($role === 'Student' && !$departments): ?>
        <div class="alert alert-warning"><i class="bi bi-exclamation-triangle"></i><div>No departments exist yet. An admin must add a department before students can register.</div></div>
    <?php endif; ?>

    <?= error_list($errors) ?>
    <form method="POST" action="register.php" class="row g-3 needs-validation" novalidate data-ajax>
        <?= csrfField() ?>
        <input type="hidden" name="role" value="<?= e($role) ?>">

        <div class="col-md-6">
            <label class="form-label" for="name">Full Name<span class="req">*</span></label>
            <input type="text" id="name" name="name" class="form-control" value="<?= e($old['name']) ?>" minlength="2" maxlength="100" required>
            <div class="invalid-feedback">Please enter your full name (2-100 characters).</div>
        </div>
        <div class="col-md-6">
            <label class="form-label" for="username">Username<span class="req">*</span></label>
            <input type="text" id="username" name="username" class="form-control" value="<?= e($old['username']) ?>" pattern="[A-Za-z0-9_]{3,20}" maxlength="20" required autocomplete="username" data-check="username">
            <div class="invalid-feedback">3-20 characters: letters, numbers, underscore (and not taken).</div>
        </div>

        <?php if ($role === 'Student'): ?>
        <div class="col-md-6">
            <label class="form-label" for="email">Email<span class="req">*</span></label>
            <input type="email" id="email" name="email" class="form-control" value="<?= e($old['email']) ?>" maxlength="100" required placeholder="name@example.com" data-check="email">
            <div class="invalid-feedback">Please enter a valid email address that is not already registered.</div>
        </div>
        <div class="col-md-6">
            <label class="form-label" for="deptid">Department<span class="req">*</span></label>
            <select id="deptid" name="deptid" class="form-select" required>
                <option value="">Select department</option>
                <?php foreach ($departments as $d): ?>
                    <option value="<?= e($d['deptid']) ?>" <?= $old['deptid'] === $d['deptid'] ? 'selected' : '' ?>>
                        <?= e($d['deptname']) ?> — <?= e($d['facultyname']) ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <div class="invalid-feedback">Please select your department.</div>
        </div>
        <div class="col-md-6">
            <label class="form-label" for="semester">Semester<span class="req">*</span></label>
            <input type="number" id="semester" name="semester" class="form-control" value="<?= e($old['semester']) ?>" min="1" max="12" step="1" required>
            <div class="invalid-feedback">Semester must be 1 to 12.</div>
        </div>
        <div class="col-md-6">
            <label class="form-label" for="cgpa">Current CGPA<span class="req">*</span></label>
            <input type="number" id="cgpa" name="cgpa" class="form-control" value="<?= e($old['cgpa']) ?>" min="0" max="4" step="0.01" required placeholder="e.g. 3.75">
            <div class="invalid-feedback">CGPA must be between 0.00 and 4.00.</div>
        </div>
        <?php else: ?>
        <div class="col-12">
            <label class="form-label" for="admin_code">Admin Registration Code<span class="req">*</span></label>
            <input type="password" id="admin_code" name="admin_code" class="form-control" required autocomplete="off">
            <div class="form-text">Provided by the system owner. It prevents unauthorised admin sign-ups.</div>
            <div class="invalid-feedback">The admin registration code is required.</div>
        </div>
        <?php endif; ?>

        <div class="col-md-6">
            <label class="form-label" for="password">Password<span class="req">*</span></label>
            <div class="password-field">
                <input type="password" id="password" name="password" class="form-control" minlength="6" maxlength="72" required autocomplete="new-password">
                <button type="button" class="password-toggle" aria-label="Show password"><i class="bi bi-eye"></i></button>
            </div>
            <div class="form-text">At least 6 characters.</div>
        </div>
        <div class="col-md-6">
            <label class="form-label" for="confirm_password">Confirm Password<span class="req">*</span></label>
            <input type="password" id="confirm_password" name="confirm_password" class="form-control" minlength="6" maxlength="72" required autocomplete="new-password">
            <div class="invalid-feedback">Passwords must match.</div>
        </div>
        <div class="col-12 mt-4">
            <button type="submit" class="btn btn-primary btn-lg w-100" data-busy="Creating account…">Create <?= e(strtolower($role)) ?> account</button>
        </div>
    </form>
    <p class="auth-footer-text">Already have an account? <a href="login.php?role=<?= e($role) ?>">Sign in</a></p>
<?php auth_close(); ?>
<?php page_end(); ?>
