SQL> 
SQL> BEGIN
  2    DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SEGMENT_ATTRIBUTES', FALSE);
  3    DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'STORAGE', FALSE);
  4    DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'TABLESPACE', FALSE);
  5    DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SQLTERMINATOR', TRUE);
  6  END;
  7  /
SQL> 
SQL> SELECT DBMS_METADATA.GET_DDL('SEQUENCE', sequence_name) FROM user_sequences;

   CREATE SEQUENCE  "AB"."SEQ_USERID"  MINVALUE 1 MAXVALUE 999999999999999999999
999999 INCREMENT BY 1 START WITH 11 NOCACHE  NOORDER  NOCYCLE ;



   CREATE SEQUENCE  "AB"."SEQ_DEPTID"  MINVALUE 1 MAXVALUE 999999999999999999999
999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE ;



   CREATE SEQUENCE  "AB"."SEQ_ADMINID"  MINVALUE 1 MAXVALUE 99999999999999999999
9999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE ;



   CREATE SEQUENCE  "AB"."SEQ_STUDENTID"  MINVALUE 1 MAXVALUE 999999999999999999
999999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE ;



   CREATE SEQUENCE  "AB"."SEQ_SCHOLARSHIPID"  MINVALUE 1 MAXVALUE 99999999999999
9999999999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE ;



   CREATE SEQUENCE  "AB"."SEQ_APPID"  MINVALUE 1 MAXVALUE 9999999999999999999999
99999 INCREMENT BY 1 START WITH 7 NOCACHE  NOORDER  NOCYCLE ;


SQL> SELECT DBMS_METADATA.GET_DDL('TABLE', table_name) FROM user_tables;

  CREATE TABLE "AB"."USERS"
   (	"USERID" NUMBER,
	"USERNAME" VARCHAR2(50) NOT NULL ENABLE,
	"PASSWORDHASH" VARCHAR2(255) NOT NULL ENABLE,
	"ROLE" VARCHAR2(20) NOT NULL ENABLE,
	 CHECK (Role IN ('Admin','Student')) ENABLE,
	 PRIMARY KEY ("USERID") ENABLE,
	 UNIQUE ("USERNAME") ENABLE
   ) ;



  CREATE TABLE "AB"."DEPARTMENT"
   (	"DEPTID" NUMBER,
	"DEPTNAME" VARCHAR2(100) NOT NULL ENABLE,
	"FACULTYNAME" VARCHAR2(100) NOT NULL ENABLE,
	 PRIMARY KEY ("DEPTID") ENABLE
   ) ;



  CREATE TABLE "AB"."ADMIN"
   (	"ADMINID" NUMBER,
	"USERID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(100) NOT NULL ENABLE,
	 PRIMARY KEY ("ADMINID") ENABLE,
	 CONSTRAINT "UQ_ADMIN_USER" UNIQUE ("USERID") ENABLE,
	 CONSTRAINT "FK_ADMIN_USERS" FOREIGN KEY ("USERID")
	  REFERENCES "AB"."USERS" ("USERID") ENABLE
   ) ;



  CREATE TABLE "AB"."STUDENT"
   (	"STUDENTID" NUMBER,
	"USERID" NUMBER NOT NULL ENABLE,
	"DEPTID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(100) NOT NULL ENABLE,
	"EMAIL" VARCHAR2(100) NOT NULL ENABLE,
	"CGPA" NUMBER(3,2),
	"SEMESTER" NUMBER(2,0) NOT NULL ENABLE,
	 CHECK (CGPA BETWEEN 0 AND 4) ENABLE,
	 PRIMARY KEY ("STUDENTID") ENABLE,
	 UNIQUE ("EMAIL") ENABLE,
	 CONSTRAINT "UQ_STUDENT_USER" UNIQUE ("USERID") ENABLE,
	 CONSTRAINT "FK_STUDENT_USERS" FOREIGN KEY ("USERID")
	  REFERENCES "AB"."USERS" ("USERID") ENABLE,
	 CONSTRAINT "FK_STUDENT_DEPT" FOREIGN KEY ("DEPTID")
	  REFERENCES "AB"."DEPARTMENT" ("DEPTID") ENABLE
   ) ;



  CREATE TABLE "AB"."SCHOLARSHIP"
   (	"SCHOLARSHIPID" NUMBER,
	"CREATEDBY" NUMBER NOT NULL ENABLE,
	"TOTALSLOTS" NUMBER NOT NULL ENABLE,
	"DEADLINE" DATE NOT NULL ENABLE,
	"AMOUNT" NUMBER(10,2) NOT NULL ENABLE,
	"TYPE" VARCHAR2(50),
	"TITLE" VARCHAR2(100) NOT NULL ENABLE,
	 PRIMARY KEY ("SCHOLARSHIPID") ENABLE,
	 CONSTRAINT "FK_SCHOLARSHIP_ADMIN" FOREIGN KEY ("CREATEDBY")
	  REFERENCES "AB"."ADMIN" ("ADMINID") ENABLE
   ) ;



  CREATE TABLE "AB"."APPLICATION"
   (	"APPID" NUMBER,
	"STUDENTID" NUMBER NOT NULL ENABLE,
	"SCHOLARSHIPID" NUMBER NOT NULL ENABLE,
	"APPROVEDBY" NUMBER,
	"APPLYDATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"STATUS" VARCHAR2(20) DEFAULT 'Pending',
	 CHECK (Status IN ('Pending','Approved','Rejected')) ENABLE,
	 PRIMARY KEY ("APPID") ENABLE,
	 CONSTRAINT "FK_APP_STUDENT" FOREIGN KEY ("STUDENTID")
	  REFERENCES "AB"."STUDENT" ("STUDENTID") ENABLE,
	 CONSTRAINT "FK_APP_SCHOLARSHIP" FOREIGN KEY ("SCHOLARSHIPID")
	  REFERENCES "AB"."SCHOLARSHIP" ("SCHOLARSHIPID") ENABLE,
	 CONSTRAINT "FK_APP_ADMIN" FOREIGN KEY ("APPROVEDBY")
	  REFERENCES "AB"."ADMIN" ("ADMINID") ENABLE
   ) ;


SQL> SELECT DBMS_METADATA.GET_DDL('REF_CONSTRAINT', constraint_name) FROM user_constraints WHERE constraint_type = 'R';

  ALTER TABLE "AB"."ADMIN" ADD CONSTRAINT "FK_ADMIN_USERS" FOREIGN KEY ("USERID"
)
	  REFERENCES "AB"."USERS" ("USERID") ENABLE;



  ALTER TABLE "AB"."STUDENT" ADD CONSTRAINT "FK_STUDENT_USERS" FOREIGN KEY ("USE
RID")
	  REFERENCES "AB"."USERS" ("USERID") ENABLE;



  ALTER TABLE "AB"."STUDENT" ADD CONSTRAINT "FK_STUDENT_DEPT" FOREIGN KEY ("DEPT
ID")
	  REFERENCES "AB"."DEPARTMENT" ("DEPTID") ENABLE;



  ALTER TABLE "AB"."SCHOLARSHIP" ADD CONSTRAINT "FK_SCHOLARSHIP_ADMIN" FOREIGN K
EY ("CREATEDBY")
	  REFERENCES "AB"."ADMIN" ("ADMINID") ENABLE;



  ALTER TABLE "AB"."APPLICATION" ADD CONSTRAINT "FK_APP_STUDENT" FOREIGN KEY ("S
TUDENTID")
	  REFERENCES "AB"."STUDENT" ("STUDENTID") ENABLE;



  ALTER TABLE "AB"."APPLICATION" ADD CONSTRAINT "FK_APP_SCHOLARSHIP" FOREIGN KEY
 ("SCHOLARSHIPID")
	  REFERENCES "AB"."SCHOLARSHIP" ("SCHOLARSHIPID") ENABLE;



  ALTER TABLE "AB"."APPLICATION" ADD CONSTRAINT "FK_APP_ADMIN" FOREIGN KEY ("APP
ROVEDBY")
	  REFERENCES "AB"."ADMIN" ("ADMINID") ENABLE;


SQL> 
SQL> SPOOL OFF
